### ISSUE TITLE
 Multiline string does not work

### ISSUE THREAD

**Issue by vanillajonathan** [jiro4989/build-rpm-action#9]
Such as having a a description that spans multiple lines.

> error: line 9: Unknown tag: This is another paragraph.

Example:
```yaml
desc: >
    This is the leading paragraph.

    This is another paragraph.
```

**Comment by jiro4989** [comment]
Thank you.
This seems to happen when the `vendor` parameter is empty.

https://github.com/jiro4989/build-rpm-action/blob/d803488448e25fcf2d89376d86adab0c6b443448/entrypoint.sh#L15

The spec file after embedding the parameters is:
https://github.com/jiro4989/build-rpm-action/actions/runs/4417536027/jobs/7743379263#step:4:1006

```
Vendor: --description:The test tools. This is sample description
and test.
```

In other words, the bug is that `--description:"$INPUT_DESC"` is passed as a value to `--vendor`.

I started fixing this bug.
It should be completed in a few days.

**Comment by jiro4989** [comment]
@vanillajonathan I fixed this bug.
Please use `jiro4989/build-rpm-action@v2` or `jiro4989/build-rpm-action@v2.3.0`.
And re-run your CI.

**Comment by vanillajonathan** [comment]
Thanks, good work!

I got it to work by adding the `vendor` property.
